### ISSUE TITLE
Set Up KanBan Board

### ISSUE THREAD

**Issue by rebaz36** [rebaz36/Capstone-M2-API#21]
# Hey Reviewer Below you can find the link to our KanBan board & Team Names

- Student A = @rebaz36
- Student B = @OscarFMdev

https://github.com/users/rebaz36/projects/2/views/1

## Thanks for Reviewing

**Comment by Qoosim** [comment]
#  *Status: Required Changes* :recycle:

H @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-  Kanban board set up correctly. :heavy_check_mark:
-  Tasks assigned correctly with appropriate headings. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] It is required to state the names of the team members in your PR as the tasks assigned. 
Ex: Student A = @rebaz36, Student B = @OscarFMdev. Kindly include that in your PR

**Comment by andersonlebon** [comment]
### Hello @rebaz36 and @OscarFMdev 
# STATUS: APPROVED! 🥇 💯
![unnamed](https://user-images.githubusercontent.com/57408419/166072781-89adf473-00b9-4579-a762-adb5d23a959d.gif)

✅ Good pull request description 👍

Your project is complete! There is nothing else to say :shipit:
Congratulations! 🎉

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

___
